# Список антибиотиков для проверки на резистентность
antibiotic_list = [
    'Penicillin', 'Oxacillin', 'Ampicillin', 'Amoxicillin',
    'Amoxicillin/Clavulanic', 'Ampicillin/Sulbactam',
    'Azlocillin', 'Carbenicillin', 'Carbenicillin-Ps', 'Ticarcillin',
    'Ticarcillin/Clavulanic', 'Mezlocillin', 'Piperacillin',
    'Piperacillin/Tazobactam', 'Imipenem', 'Meropenem',
    'Ertapenem', 'Aztreonam', 'ESβL Cft/CA', 'ESβL  Caz/CA',
    'Cephalothin', 'Cefazolin', 'Cefuroxime', 'Cefotetan',
    'Cefamandole', 'Cefoxitin', 'Cefonicid', 'Cefaclor',
    'Loracarbef', 'Cefotaxime', 'Ceftriaxone', 'Ceftizoxime',
    'Cefixime', 'Cefpodoxime', 'Cefoperazone', 'Ceftazidime',
    'Cefepime', 'Gentamicin', 'Gentamicin syn', 'Streptomyc.syn',
    'Amikacin', 'Tobramycin', 'Netilmicin', 'Spectinomycin',
    'Ciprofloxacin', 'Gatifloxacin', 'Moxifloxacin', 'Ofloxacin',
    'Lomefloxacin', 'Levofloxacin', 'Pefloxacin', 'Sparfloxacin',
    'Erytromycin', 'Clarithromycin', 'Azithromycin', 'Clindamycin',
    'Fosfomycin', 'Josamycin', 'Tetracycline', 'Minocycline',
    'Doxiciclin', 'Trimethoprim-Sulphamethoxazole',
    'Chloramphenicol', 'Rifampicin',
    'Vancomycin', 'Linezolid', 'Synercid', 'Tigecycline',
    'Daptomicin', 'Metronidazol', 'Norfloxacin', 'Cinoxacin',
    'Nalidixic Acid', 'Nitrofurantoin', 'Sulfamethoxazole', 'Trimethoprim',
    '5-НОК', 'Voriconazol', 'Amphotericin B', 'Miconazol',
    'Ketoconazole', 'Itraconazole', 'Fluconazole'
]
