from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    MAIN_EXCEL_FILE_PATH: str
    MAIN_FOLDER_PATH: str
    DIABETIC_FOOT: str
    DIABETIC_KIDNEY_DISEASE: str
    NEUROENDOCRINOLOGY: str
    ENDOCRINOPATHIES_THERAPY: str
    PATHOLOGY_OF_PARATHYROID_GLANDS: str
    ANESTHESIOLOGY_AND_RESUSCITATION_CENTER: str
    CARDIOLOGY_AND_VASCULAR_SURGERY: str
    ENDOCRINOPATHIES_OF_EARLY_AGE: str
    ANDROLOGY_AND_UROLOGY: str
    DIABETES_FORECASTING_AND_INNOVATION: str
    SURGERY: str
    ASSISTED_REPRODUCTIVE_TECHNOLOGIES: str
    THYROID_GLAND: str
    CHILDHOOD_ENDOCRINE_TUMORS: str
    PEDIATRIC_SURGERY: str
    CHILDHOOD_DIABETES_MELLITUS: str
    OSTEOPOROSIS_AND_OSTEOPATHY: str
    PEDIATRIC_THYROIDOLOGY: str

    class Config:
        env_file = '.env'


settings = Settings()
